######################################################################
# Automatically generated by qmake (3.0) mar. mai 5 21:14:42 2015
######################################################################

TEMPLATE = app
TARGET = collidingmice
INCLUDEPATH += .

# Input
QT += widgets

HEADERS += \
        mouse.h
SOURCES += \
        main.cpp \
        mouse.cpp

RESOURCES += \
        mice.qrc
